# Generated by Django 5.0.6 on 2024-06-10 01:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='restaurant', max_length=255)),
                ('platform', models.CharField(choices=[('kakaomap', 'kakaomap')], max_length=50)),
                ('place_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_rating', models.CharField(default='0.0점', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('positive_score', models.FloatField()),
                ('negative_score', models.FloatField()),
                ('neu_score', models.FloatField(default=0.0)),
                ('compound_score', models.FloatField(default=0.0)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_review.restaurant')),
            ],
        ),
    ]
