# Generated by Django 5.0.6 on 2024-06-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_review_created_at_review_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
